apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Pod
apiVersion: v1
metadata: 
  name: nginx
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
spec:
  containers:
    - name: nginx
      image: nginx
